### PR TITLE
Improved readme file

### PR DESCRIPTION
**Pull request by vqasemi**
add comments on the read me file

### CODE REVIEW

**Comment by qbrosdev** [comment]
add some bold text

**Comment by vqasemi** [comment]
added bold

**Comment by qbrosdev** [comment]
add italic

**Comment by vqasemi** [comment]
ok

**Comment by vqasemi** [comment]
italic added

**Comment by qbrosdev** [comment]
can't merge on the main branch, create a PR on a new branch

**Comment by vqasemi** [comment]
going to create a branch with name "new_feature"

**Pull request merged**
